# -*- coding: utf-8 -*-
"""WebScrapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IhacUnaQLwL6OPrRlhhR2-Dooe1xTBC
"""

!pip install beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
from google.colab import files

url = 'http://books.toscrape.com/'
response = requests.get(url)
response.raise_for_status()  # Check for request errors
soup = BeautifulSoup(response.text, 'html.parser')

books = soup.find_all('article', class_='product_pod')

book_data = []
for book in books:
    title = book.h3.a['title']
    price = book.find('p', class_='price_color').text
    availability = book.find('p', class_='instock availability').text.strip()
    book_data.append({'Title': title, 'Price': price, 'Availability': availability})

df = pd.DataFrame(book_data)

print("Scraped Data:")
print(df)

csv_file = 'books_data.csv'
df.to_csv(csv_file, index=False)

files.download(csv_file)